### ISSUE TITLE
[Feature Suggestion] Remove Pokémon from List

### ISSUE THREAD

**Issue by bellyrose** [PoshoDev/DexTool#1]
I was wondering if it'd be possible to remove Pokémon from the National dex list, specifically all the GMax forms. They're not a form that stays out of battle so I don't use it in Living Dexes, similar to megas.

**Comment by PoshoDev** [comment]
Hey there! 🙂I assumed the universe had forgotten about DexTool. 😅

Non-battle forms have been in the bucket list for a while but I never got around to working on them because they weren't requested until now. I'm very busy this week, but I'll try to do my best to bring the feature by the end of this week. 👍

**Comment by PoshoDev** [comment]
Hey there, I managed to get on to this much earlier than I expected. I added the option to toggle between displaying Gigantamax forms by pressing "G". I'll work on options to make the process more straightforward, but right now my priority was to just allow you to use the feature right away. 🙂

You can find the [new release here](https://github.com/PoshoDev/DexTool/releases/tag/v0.4.1-alpha). Hope you find it useful, thank you for using my tool, it means a lot!
